# Generated by Django 6.0.4 on 2026-04-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_open',
            new_name='is_registration_open',
        ),
        migrations.RemoveField(
            model_name='game',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='player',
            name='balance',
        ),
        migrations.AddField(
            model_name='game',
            name='distribution_option',
            field=models.CharField(choices=[('1', 'Escolha Livre (Equipa 1 ou 2)'), ('2', 'Auto-Balanceamento por Estatísticas'), ('3', 'Inscrição de Equipa Inteira')], default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='max_players_per_team',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='game',
            name='max_subs_per_team',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='sport',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente (Aguardar admin)'), ('ACCEPTED', 'Aceite (Aguardar pagamento)'), ('PAID', 'Pago (Inscrição Válida)'), ('INVALID', 'Inválida (Expirou tempo de pagamento)')], default='PENDING', max_length=10)),
                ('selected_side', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
