# Generated by Django 6.0.4 on 2026-04-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_is_open_game_is_registration_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='player',
            name='sport_positions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='player',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
