# Generated by Django 6.0.5 on 2026-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='caption',
        ),
        migrations.AddField(
            model_name='highlight',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='modality',
            field=models.CharField(default='Futebol', max_length=50),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='highlights/'),
        ),
    ]
