# Generated by Django 6.0.4 on 2026-04-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_age_player_gender_player_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='jcruz', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
