# Generated by Django 6.0.5 on 2026-05-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_highlight_caption_highlight_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_highlights', to='api.player'),
        ),
    ]
