# Generated by Django 6.0.4 on 2026-05-01 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='api.player'),
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceite'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='api.player')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='api.player')),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
