# Generated by Django 6.0.5 on 2026-05-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('FOLLOW_REQUEST', 'Follow Request'), ('TEAM_JOIN_REQUEST', 'Team Join Request'), ('REGISTRATION', 'Registration'), ('GENERAL', 'General')], max_length=30, null=True),
        ),
    ]
