# Generated by Django 6.0.4 on 2026-05-01 18:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_player_followers_followrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='distribution_option',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_registration_open',
        ),
        migrations.RemoveField(
            model_name='game',
            name='max_players_per_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='max_subs_per_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sport',
        ),
        migrations.AddField(
            model_name='game',
            name='cor_equipa1',
            field=models.CharField(default='#ff0000', max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='cor_equipa2',
            field=models.CharField(default='#0000ff', max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 1, 18, 53, 52, 712378, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='distribution_model',
            field=models.CharField(default='Escolha Livre', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='modality',
            field=models.CharField(default='Futebol', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='occupiedPositions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='game',
            name='suplentes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.time(18, 54, 53, 689758)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='titulares',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='game',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_games', to='api.player'),
        ),
    ]
