# Generated by Django 6.0.4 on 2026-05-02 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_game_distribution_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='selected_side',
        ),
        migrations.AddField(
            model_name='registration',
            name='position_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_registrations', to='api.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aceite'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_registrations', to='api.team'),
        ),
    ]
