# Generated by Django 6.0.5 on 2026-05-20 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='payment_deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='registration_deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_receipt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Por pagar'), ('PAID', 'Pago'), ('OVERDUE', 'Não pago')], default='PENDING', max_length=15),
        ),
    ]
