# Generated by Django 6.0.4 on 2026-05-04 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_teamjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='modality_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='highlights/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='api.player')),
            ],
        ),
    ]
